"""agrega_verificacion_registro

Revision ID: 07e9db670b45
Revises: a376f6ad6ab3
Create Date: 2026-04-23 14:12:31.897243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07e9db670b45'
down_revision: Union[str, None] = 'a376f6ad6ab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
