"""agrega columna telefono a usuarios

Revision ID: a376f6ad6ab3
Revises: 
Create Date: 2026-04-22 12:30:59.729241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a376f6ad6ab3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('telefono', sa.String(length=20), nullable=True))
    op.add_column('usuarios', sa.Column('password_reset_token', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_usuarios_telefono'), 'usuarios', ['telefono'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_telefono'), table_name='usuarios')
    op.drop_column('usuarios', 'password_reset_token')
    op.drop_column('usuarios', 'telefono')
    # ### end Alembic commands ###
